# Generated by Django 3.1.1 on 2020-12-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_status', models.CharField(default='Pending', max_length=5000)),
                ('query_type', models.CharField(default='', max_length=5000)),
                ('query_desc', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=90)),
                ('email', models.CharField(default='', max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
                ('roll_number', models.CharField(default='', max_length=111)),
                ('branchyear', models.CharField(default='', max_length=111)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
