# Generated by Django 3.1.1 on 2020-12-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cne', '0002_auto_20201218_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactcomplain',
            old_name='roll_number',
            new_name='rollnumber',
        ),
        migrations.RenameField(
            model_name='contactenquiry',
            old_name='roll_number',
            new_name='rollnumber',
        ),
    ]
