# Generated by Django 3.1.1 on 2020-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cne', '0003_auto_20201218_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactcomplain',
            old_name='query_desc',
            new_name='querydesc',
        ),
        migrations.RenameField(
            model_name='contactcomplain',
            old_name='query_type',
            new_name='querytype',
        ),
        migrations.RenameField(
            model_name='contactenquiry',
            old_name='query_desc',
            new_name='querydesc',
        ),
        migrations.RenameField(
            model_name='contactenquiry',
            old_name='query_type',
            new_name='querytype',
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='query_status',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
