# Generated by Django 3.1.1 on 2020-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cne', '0004_auto_20201218_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcomplain',
            name='querysub',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='querysub',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
