# Generated by Django 3.1.1 on 2020-11-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=50)),
                ('roll_number', models.IntegerField(default='', max_length=50)),
                ('sub1_name', models.CharField(default='', max_length=50)),
                ('sub2_name', models.CharField(default='', max_length=50)),
                ('sub3_name', models.CharField(default='', max_length=50)),
                ('sub1_marks', models.IntegerField(default='', max_length=50)),
                ('sub2_marks', models.IntegerField(default='', max_length=50)),
                ('sub3_marks', models.IntegerField(default='', max_length=50)),
                ('pub_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
