# Generated by Django 3.1.1 on 2020-12-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_name', models.CharField(default='', max_length=50)),
                ('notes_sub', models.CharField(default='', max_length=50)),
                ('notes_desc', models.CharField(default='', max_length=300)),
                ('notes_image', models.ImageField(blank=True, null=True, upload_to='notes/images')),
                ('pub_date', models.DateTimeField(null=True)),
                ('notes_document', models.FileField(blank=True, null=True, upload_to='notes/images')),
            ],
        ),
    ]
