# Generated by Django 3.1.1 on 2020-12-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='order_id',
            new_name='fee_id',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='phone',
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_desc',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_sub',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
