# Generated by Django 3.1.1 on 2020-12-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_auto_20201204_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='FEES',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_sub', models.CharField(default='', max_length=50)),
                ('fee_desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='FEE',
        ),
        migrations.AlterField(
            model_name='feeupdate',
            name='update_desc',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
