# Generated by Django 3.1.1 on 2020-12-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0003_auto_20201204_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='fee_document',
            field=models.FileField(blank=True, null=True, upload_to='fee/images'),
        ),
    ]
