# Generated by Django 3.1.1 on 2020-12-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0004_fees_fee_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(default='', max_length=5000)),
                ('amount', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
