# Generated by Django 3.1.1 on 2020-12-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0008_auto_20201205_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='items_json',
        ),
    ]
