# Generated by Django 3.1.1 on 2020-12-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0009_remove_payments_items_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeupdate',
            name='address',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AddField(
            model_name='feeupdate',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feeupdate',
            name='email',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AddField(
            model_name='feeupdate',
            name='name',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AddField(
            model_name='feeupdate',
            name='phone',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AddField(
            model_name='feeupdate',
            name='roll_number',
            field=models.CharField(default='', max_length=111),
        ),
    ]
