# Generated by Django 3.1.1 on 2020-10-28 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(default='', upload_to='clubs/images'),
        ),
        migrations.AddField(
            model_name='group',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
