# Generated by Django 3.1.1 on 2020-10-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20201028_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='document',
            field=models.FileField(default='', upload_to='clubs/documents'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='', upload_to='clubs/images'),
        ),
    ]
