# Generated by Django 3.1.1 on 2020-10-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20201031_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='document',
            field=models.FileField(blank=True, default='', upload_to='clubs/documents'),
        ),
    ]
