# Generated by Django 3.1.1 on 2020-10-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20201031_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
