# Generated by Django 3.1.1 on 2020-10-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20201031_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='document',
        ),
        migrations.RemoveField(
            model_name='group',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='', upload_to='clubs/images'),
        ),
    ]
