# Generated by Django 3.1.1 on 2020-10-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20201031_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=300)),
                ('pub_date', models.DateTimeField()),
                ('document', models.FileField(default='', upload_to='clubs/documents')),
            ],
        ),
    ]
