# Generated by Django 3.1.1 on 2020-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20201031_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CNotice',
        ),
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='document',
            field=models.FileField(default='', upload_to='clubs/documents'),
        ),
        migrations.AddField(
            model_name='group',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
