# Generated by Django 3.1.1 on 2020-11-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20201031_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='LF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=50)),
                ('item_category', models.CharField(default='', max_length=50)),
                ('item_desc', models.CharField(default='', max_length=300)),
                ('item_image', models.ImageField(null='True', upload_to='clubs/lostfound')),
                ('pub_date', models.DateTimeField()),
                ('item_document', models.FileField(null='True', upload_to='clubs/lostfound')),
            ],
        ),
    ]
