# Generated by Django 3.1.1 on 2020-11-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_lf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LF',
        ),
    ]
