# Generated by Django 3.1.1 on 2020-11-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20201105_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='clubs/images'),
        ),
    ]
