# Generated by Django 3.1.1 on 2020-12-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20201108_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='coordinator',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='group',
            name='detaileddesc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
